# Generated by Django 5.0.4 on 2025-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('wellness', 'Wellness'), ('fitness', 'Fitness'), ('beauty', 'Beauty'), ('therapy', 'Therapy')], max_length=50)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('gallery', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('includes', models.JSONField(default=list)),
                ('schedule', models.JSONField(default=list)),
            ],
        ),
    ]
