# Generated by Django 5.0.4 on 2025-04-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_room_customuser_is_checked_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_occupied',
            new_name='occupied',
        ),
    ]
