# Generated by Django 5.0.4 on 2025-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_room_current_guest_checkinlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
